#!/bin/env bash

usage() {
  echo "USAGE: $0 (" >&2
  echo "         install <repository_url>" >&2
  echo "       )" >&2
  exit 1
}

log() {
  echo "[$(date '+%F %T')] $1"
}

(($# < 1)) && usage
command=$1
shift

(($# < 1)) && usage
repository_url=$1
export repository_url
shift

(($# >= 1)) && usage

#

log "Repository URL: $repository_url"

# リポジトリJSONファイル読み取り
log "Fetching: $repository_url"
repository_json=$(curl -s "$repository_url")
(($? == 0)) || exit
export repository_json

# リポジトリ名
repository_name=$(fl7 '&FROM_JSON(ENV.repository_json).name | *URI')
(($? == 0)) || exit
export repository_name
log "Repository Name: $repository_name"

# リポジトリ格納ディレクトリ
repository_dir=fl7_modules/_$(fl7 '&FROM_JSON(ENV.repository_json).name | *URI | REPLACE(_; /[^a-zA-Z0-9_%]/g; \"%$%02s(UC(BASE(CHARCODE(_); 16)))")')
(($? == 0)) || exit
export repository_dir
log "Repository Dir: $repository_dir"

# リポジトリ格納ディレクトリがある場合は削除
if [ -d "$repository_dir" ]
then
  log "Removing $repository_dir"
  rm -rf "$repository_dir" || exit
fi

# リポジトリ格納ディレクトリ作成
log "Making $repository_dir"
mkdir -p "$repository_dir" || exit

# リポジトリファイル
list_url_file=($(fl7 'FROM_JSON(ENV.repository_json).files[] | &_ | *URI | REPLACE(_; /[^a-zA-Z0-9_%]/g; \"%$%02s(UC(BASE(CHARCODE(_); 16)))") => JOIN >> " "'))
(($? == 0)) || exit

# ダウンロード
for url_file in "${list_url_file[@]}"
do

  export url_file

  # 実際のファイル名
  file=$(fl7 '
    s : (ENV.url_file | *FROM_URI);
    s =~ /^([^\/]+(?:\/[^\/]+)*)$/ ?: ERROR("Illegal file name: $s");
    +([SPLIT(s; "/")] | "." @ _ || ".." @ _) && ERROR("Illegal file name: $s");
    s
  ')
  (($? == 0)) || exit

  # ダウンロード元
  url_absolute_file=$(fl7 'ENV.repository_url =~ /^([a-zA-Z0-9_]+:\/\/[^\/]+)(\/.*)$/ | _.1 & RESOLVE(_.2, "..", (ENV.url_file | *FROM_URI)) | "?" @ _ ? _ : "$_?"')
  (($? == 0)) || exit

  # ダウンロード
  log "Downloading $url_absolute_file -> $repository_dir/$file"
  curl -s "$url_absolute_file" > "$repository_dir/$file" || exit

done

log "Successfully Installed"

exit 0
